apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: flopez/nginx:latest
    from:
      kind: DockerImage
      name: flopez/nginx:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
status:
  dockerImageRepository: ""
